function createfigure(XData1, YData1, YData2)
%CREATEFIGURE(XData1, YData1, YData2)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  YDATA2:  line ydata

%  Auto-generated by MATLAB on 17-May-2022 13:38:16

% Create figure
figure1 = figure('Tag','MLearnAppExportedResponsePlot');

% Create axes
axes1 = axes('Tag','MLearnAppExportedResponsePlotAxes','Parent',figure1);

% Create line
line(XData1,YData1,'DisplayName','True',...
    'Tag','MLearnAppTracePlotTrainingDataTrace',...
    'Parent',axes1,...
    'MarkerSize',18,...
    'Marker','.',...
    'LineStyle','none',...
    'Color',[0 0.447 0.741]);

% Create line
line(XData1,YData2,'DisplayName','Predicted',...
    'Tag','MLearnAppTracePlotPredictionsTrace',...
    'Parent',axes1,...
    'MarkerSize',18,...
    'Marker','.',...
    'LineStyle','none',...
    'Color',[0.929 0.694 0.125]);

% Create ylabel
ylabel('Response (attendance)','Interpreter','none');

% Create xlabel
xlabel('Record number','Interpreter','none');

% Create title
title('Predictions: model 1 (Linear)','Interpreter','none');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-11.35 260.35]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-7.21789496423614 2.96635242935503]);
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'OuterPosition',[0 0 0.858916665140788 1]);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','northeastoutside');

